import fs from 'fs';

let appJs = fs.readFileSync('app/static/app.js', 'utf8');

// We will redesign the MoneyControl blocks to show all URLs generated by the scraper.
// Replace the current mcBsEl and mcPnlEl rendering.
const target = `  if (mc.found) {
    mcBsEl.innerHTML = \`
      <div style="display:flex;flex-direction:column;gap:0.75rem;padding:0.5rem 0;">
        <div style="font-size:0.9rem;"><strong>Matched Entity:</strong> \${mc.company_name}</div>
        <div style="font-size:0.85rem;color:var(--text-muted);"><strong>Sector:</strong> \${mc.sector} &nbsp;|&nbsp; <strong>MC Stock ID:</strong> \${mc.sc_id}</div>
        <div style="display:flex;gap:0.5rem;flex-wrap:wrap;margin-top:0.5rem;">
          <a href="\${mc.balance_sheet_url}" target="_blank" class="search-btn" style="text-decoration:none;font-size:0.8rem;padding:0.5rem 1rem;"><i class="fa-solid fa-scale-balanced"></i> Open MC Balance Sheet</a>
          <a href="\${mc.cash_flow_url}" target="_blank" class="search-btn" style="text-decoration:none;font-size:0.8rem;padding:0.5rem 1rem;background:rgba(16,185,129,0.2);border-color:var(--accent-emerald);"><i class="fa-solid fa-money-bill-transfer"></i> Open MC Cash Flow</a>
        </div>
      </div>
    \`;

    mcPnlEl.innerHTML = \`
      <div style="display:flex;flex-direction:column;gap:0.75rem;padding:0.5rem 0;">
        <div style="font-size:0.9rem;"><strong>Matched Entity:</strong> \${mc.company_name}</div>
        <div style="font-size:0.85rem;color:var(--text-muted);"><strong>Sector:</strong> \${mc.sector} &nbsp;|&nbsp; <strong>MC Stock ID:</strong> \${mc.sc_id}</div>
        <div style="display:flex;gap:0.5rem;flex-wrap:wrap;margin-top:0.5rem;">
          <a href="\${mc.profit_loss_url}" target="_blank" class="search-btn" style="text-decoration:none;font-size:0.8rem;padding:0.5rem 1rem;"><i class="fa-solid fa-chart-line"></i> Open MC Profit & Loss</a>
          <a href="\${mc.ratios_url}" target="_blank" class="search-btn" style="text-decoration:none;font-size:0.8rem;padding:0.5rem 1rem;background:rgba(139,92,246,0.2);border-color:var(--accent-purple);"><i class="fa-solid fa-percent"></i> Open MC Ratios</a>
        </div>
      </div>
    \`;`;

const replacement = `  if (mc.found) {
    mcBsEl.innerHTML = \`
      <div style="display:flex;flex-direction:column;gap:1rem;padding:0.5rem 0;">
        <div style="font-size:0.95rem; border-bottom: 1px solid rgba(255,255,255,0.1); padding-bottom: 0.5rem;">
           <strong><i class="fa-solid fa-building"></i> MoneyControl Entity:</strong> \${mc.company_name}
        </div>
        <div style="font-size:0.85rem;color:var(--text-muted); display:flex; gap: 1rem;">
           <span><strong>Sector:</strong> <span style="color:var(--accent-amber);">\${mc.sector}</span></span>
           <span><strong>MC Stock ID:</strong> <span style="color:var(--accent-cyan);">\${mc.sc_id}</span></span>
        </div>
        <div style="display:flex;gap:0.5rem;flex-wrap:wrap;margin-top:0.5rem;">
          <a href="\${mc.stock_url}" target="_blank" class="search-btn" style="text-decoration:none;font-size:0.8rem;padding:0.5rem 1rem;background:rgba(245,158,11,0.2);border-color:var(--accent-amber);"><i class="fa-solid fa-house"></i> MC Main Hub</a>
          <a href="\${mc.balance_sheet_url}" target="_blank" class="search-btn" style="text-decoration:none;font-size:0.8rem;padding:0.5rem 1rem;"><i class="fa-solid fa-scale-balanced"></i> Balance Sheet</a>
          <a href="\${mc.cash_flow_url}" target="_blank" class="search-btn" style="text-decoration:none;font-size:0.8rem;padding:0.5rem 1rem;background:rgba(16,185,129,0.2);border-color:var(--accent-emerald);"><i class="fa-solid fa-money-bill-transfer"></i> Cash Flow</a>
        </div>
      </div>
    \`;

    mcPnlEl.innerHTML = \`
      <div style="display:flex;flex-direction:column;gap:1rem;padding:0.5rem 0;">
        <div style="font-size:0.95rem; border-bottom: 1px solid rgba(255,255,255,0.1); padding-bottom: 0.5rem;">
           <strong><i class="fa-solid fa-chart-line"></i> MoneyControl Performance Links</strong>
        </div>
        <div style="display:flex;gap:0.5rem;flex-wrap:wrap;margin-top:0.5rem;">
          <a href="\${mc.profit_loss_url}" target="_blank" class="search-btn" style="text-decoration:none;font-size:0.8rem;padding:0.5rem 1rem;background:rgba(6,182,212,0.2);border-color:var(--accent-cyan);"><i class="fa-solid fa-chart-line"></i> Profit & Loss</a>
          <a href="\${mc.ratios_url}" target="_blank" class="search-btn" style="text-decoration:none;font-size:0.8rem;padding:0.5rem 1rem;background:rgba(139,92,246,0.2);border-color:var(--accent-purple);"><i class="fa-solid fa-percent"></i> Financial Ratios</a>
          <a href="\${mc.quarterly_url}" target="_blank" class="search-btn" style="text-decoration:none;font-size:0.8rem;padding:0.5rem 1rem;background:rgba(236,72,153,0.2);border-color:var(--accent-pink);"><i class="fa-solid fa-calendar-days"></i> Quarterly Results</a>
          <a href="\${mc.stock_url + '/peer-comparison'}" target="_blank" class="search-btn" style="text-decoration:none;font-size:0.8rem;padding:0.5rem 1rem;background:rgba(245,158,11,0.2);border-color:var(--accent-amber);"><i class="fa-solid fa-users"></i> Peer Comparison</a>
        </div>
      </div>
    \`;`;

if (appJs.includes('if (mc.found) {') && appJs.includes('mcBsEl.innerHTML =')) {
    appJs = appJs.replace(target, replacement);
    fs.writeFileSync('app/static/app.js', appJs);
    console.log("Success");
} else {
    console.log("Target not found");
}

