const fs = require('fs');

const deepTooltips = {
  "Market Cap": {
    "meaning": "Market Capitalization represents the aggregate market value of a company’s outstanding equity at a specific point in time. It is calculated by multiplying the prevailing market price per share by the total number of outstanding shares. Rather than focusing on the absolute price of a single equity unit, Market Cap provides a macro-level assessment of the firm's total equity valuation. It serves as a continuous real-time proxy for the collective consensus of institutional and retail investors regarding the net present value of all anticipated future free cash flows, discounted back to today, adjusting for ongoing systemic and idiosyncratic risk premiums.",
    "relevance": "Institutional investors and asset managers utilize Market Capitalization to classify equities into distinct asset classes (Large-Cap, Mid-Cap, Small-Cap, and Micro-Cap), which inherently dictate capital allocation strategies, benchmark index inclusions, and portfolio risk profiling. Mega-cap and large-cap equities typically offer lower structural volatility, robust balance sheet resilience, and stable dividend distributions, acting as defensive anchors during macroeconomic contractions. Conversely, small-cap and micro-cap equities introduce heightened systematic risk, lower secondary market liquidity, and higher probability of insolvency, but concurrently offer substantial alpha-generation potential and asymmetric upside for investors willing to underwrite the elevated volatility and execution risk."
  },
  "Current Price": {
    "meaning": "The Current Price denotes the most recent transactional clearing price executed on the secondary market exchange. It is the real-time equilibrium point where the marginal buyer's willingness to pay perfectly intersects with the marginal seller's willingness to liquidate. This nominal figure, in isolation, is entirely devoid of intrinsic fundamental meaning, as corporate actions such as stock splits, bonus issuances, or reverse splits can arbitrarily alter the outstanding share count and consequently manipulate the per-share price without fundamentally changing the enterprise's aggregate underlying valuation or operational earning power.",
    "relevance": "In rigorous fundamental analysis, the Current Price serves exclusively as the numerator or denominator for critical valuation multiples (such as the Price-to-Earnings, Price-to-Book, and Price-to-Free-Cash-Flow ratios) or as the comparative benchmark against a calculated intrinsic value estimate (like a Discounted Cash Flow output). Institutional analysts monitor price velocity and momentum strictly in the context of identifying market mispricings—seeking discrepancies where the quoted market price significantly diverges from the underlying asset's mathematically modeled intrinsic value, thereby presenting a statistical arbitrage or long-term value-accretive acquisition opportunity."
  },
  "High / Low": {
    "meaning": "The 52-Week High and Low establishes the absolute peak-to-trough price variance of an equity over a trailing twelve-month trailing continuum. It meticulously maps the extremity of market psychology, capturing periods of irrational exuberance (peak multiples expansion) and capitulatory panic (peak multiples contraction) driven by macroeconomic cycles, earnings surprises, or systemic liquidity shocks. This metric establishes historical resistance and support boundaries, delineating the maximum historical threshold investors were willing to underwrite before reversing their capital flows.",
    "relevance": "Quantitative and fundamental strategists monitor 52-week price extremes to diagnose broader market sentiment, momentum anomalies, and potential mean-reversion triggers. When an equity approaches its 52-week low, it generally flags severe operational distress, macroeconomic headwinds, or acute institutional distribution—creating either a compelling deep-value acquisition zone with a wide margin of safety or, conversely, signaling a structural value trap. Approaching a 52-week high typically confirms robust fundamental execution, positive earnings momentum, and institutional accumulation, though it simultaneously warns of potential multiple over-extension and diminished prospective risk-adjusted forward returns."
  },
  "Stock P/E": {
    "meaning": "The Price-to-Earnings (P/E) ratio is a primary valuation heuristic that quantifies the multiple of trailing or forward net income the market demands to acquire the equity. Calculated by dividing the current market capitalization by aggregate net income (or price per share by earnings per share), it encapsulates the exact premium investors are willing to pay for one dollar of corporate earnings. A P/E expansion implies the market is pricing in accelerating future growth trajectories, lower capital costs, or a durable expansion in return on invested capital, while a contraction indicates deteriorating fundamentals or rising systemic discount rates.",
    "relevance": "Institutional analysts utilize the P/E ratio for relative peer-group benchmarking and historical time-series valuation analysis. An elevated P/E multiple suggests the market is deeply discounting rapid, frictionless future growth; however, it inherently drastically reduces the investor's margin of safety, rendering the equity hypersensitive to minor earnings misses or macroeconomic yield shocks. Conversely, a suppressed P/E multiple often highlights market pessimism or secular decline, forcing analysts to aggressively parse the financial statements to differentiate between a temporarily mispriced, capital-efficient franchise and a structurally impaired enterprise facing terminal obsolescence."
  },
  "Book Value": {
    "meaning": "Book Value per Share represents the theoretical liquidation threshold of the enterprise. It is strictly calculated by stripping away all total liabilities and intangible assets (such as goodwill or brand value) from the total tangible assets on the balance sheet, then dividing the residual shareholder equity by the outstanding share count. This accounting metric anchors the firm to its historical cost basis, illustrating the exact sum of retained earnings and paid-in capital amassed since inception, devoid of future growth speculation or forward-looking market sentiment.",
    "relevance": "In deep-value and distress investing frameworks, Book Value acts as the definitive downside protection floor. Purchasing equities at a steep discount to their Book Value implies acquiring tangible assets (cash, real estate, machinery) for less than their nominal accounting worth—an arbitrage popularized by Benjamin Graham. However, in the modern macroeconomic environment dominated by asset-light, intellectual-property-driven technology and service sectors, Book Value routinely understates true economic value, requiring analysts to augment it with return on invested capital (ROIC) assessments and off-balance-sheet intangible asset valuations."
  },
  "Dividend Yield": {
    "meaning": "Dividend Yield is the financial ratio that expresses the annualized quantum of cash dividends disbursed to shareholders relative to the equity's current secondary market price. It represents the immediate, realized cash return on investment, entirely independent of capital appreciation or secondary market price volatility. Yield is fundamentally a capital allocation decision by the board of directors, signaling that the enterprise generates excess free cash flow beyond what can be accretively reinvested into organic operations at a return exceeding the firm's cost of capital.",
    "relevance": "Yield-focused institutions and fixed-income proxy portfolios aggressively monitor this metric to model predictable liquidity streams and total return profiles. A high, sustainable dividend yield often characterizes mature, capital-intensive monopolies (utilities, telecommunications) operating in low-growth, highly regulated environments. Conversely, a sudden, anomalous spike in dividend yield is frequently a 'yield trap'—a mechanical illusion caused by a collapsing stock price accurately forecasting an imminent, severe dividend cut due to deteriorating underlying free cash flow generation."
  },
  "ROCE": {
    "meaning": "Return on Capital Employed (ROCE) is an elite profitability ratio that measures the pre-tax operational efficiency of a firm relative to the aggregate capital deployed, encompassing both shareholder equity and interest-bearing debt. Calculated as Earnings Before Interest and Taxes (EBIT) divided by total Capital Employed (Total Assets minus Current Liabilities), it strictly isolates the core operational engine's horsepower. ROCE neutralizes distortions caused by varying corporate capital structures or localized tax regimes, providing an unadulterated view of how effectively management allocates scarce capital to generate operating profit.",
    "relevance": "ROCE is widely regarded by fundamental analysts as the definitive proxy for assessing a corporation's structural economic moat and pricing power. A business consistently maintaining a ROCE substantially above its Weighted Average Cost of Capital (WACC) is actively creating intrinsic economic value, compounding wealth organically. Conversely, a firm generating a ROCE below its WACC is structurally destroying shareholder value with every dollar it invests, signaling fierce commoditization, obsolete technology, or catastrophic management capital allocation, regardless of absolute revenue growth."
  },
  "ROE": {
    "meaning": "Return on Equity (ROE) quantifies a corporation's profitability strictly from the perspective of the common shareholder. Computed by dividing net income by total shareholder equity, it delineates the exact bottom-line return generated on the residual capital invested by the owners. Unlike ROCE, ROE is profoundly sensitive to financial leverage; it incorporates the burdens of interest expense and the amplifying effects of debt financing, isolating the ultimate cash-on-cash yield attributable solely to the equity tranche of the capital structure.",
    "relevance": "While ROE is the most direct measure of compounding velocity for equity holders, sophisticated analysts view it with extreme caution due to its susceptibility to artificial inflation via excessive debt loading. A superficially stellar ROE driven by a razor-thin equity base and massive, unhedged borrowing masks extreme insolvency risk. Therefore, institutional analysts perpetually deconstruct ROE using the DuPont framework to rigorously verify whether the returns stem from genuine operational margin expansion and asset velocity, or merely from the dangerous deployment of highly leveraged financial engineering."
  },
  "Face Value": {
    "meaning": "Face Value, or par value, is the nominal, static accounting value arbitrarily assigned to a single unit of equity upon the initial corporate formation and chartering. It dictates the fundamental legal baseline for the firm's stated capital account on the balance sheet. Unlike market capitalization, which dynamically fluctuates with global liquidity and microeconomic data, the face value remains completely rigid and is utterly disconnected from the enterprise’s ongoing operational profitability, free cash flow generation, or secondary market valuation.",
    "relevance": "While completely irrelevant to assessing an equity's current intrinsic value or forward trading dynamics, Face Value retains crucial structural importance in corporate accounting mechanics. It serves as the unyielding mathematical baseline for corporate actions; when a board of directors declares a dividend percentage (e.g., a '200% dividend') or executes a stock split (e.g., splitting a $10 face value into ten $1 shares to increase liquidity), the calculations are executed strictly against this historical par value, completely ignoring the prevailing market clearing price."
  },
  "Debtor Days": {
    "meaning": "Debtor Days, or Days Sales Outstanding (DSO), is a stringent working capital efficiency metric that calculates the weighted average duration required for a corporation to collect actual cash remittances following the execution of a credit sale. It mathematically tracks the velocity of accounts receivable, illuminating the exact temporal lag between recognizing top-line accounting revenue and physically securing the corresponding liquidity in the corporate treasury.",
    "relevance": "Institutional analysts monitor Debtor Days as a high-fidelity leading indicator of underlying operational health and customer solvency. A structural expansion in this metric is a severe red flag, suggesting that management is aggressively recognizing low-quality revenue via lenient credit terms to artificially inflate top-line growth (channel stuffing), or that the core customer base is experiencing acute financial distress. Prolonged debtor cycles drastically impair free cash flow conversion, forcing the enterprise to rely on expensive external bridge financing to maintain operational liquidity."
  },
  "Inventory Days": {
    "meaning": "Inventory Days, or Days Sales of Inventory (DSI), measures the exact number of days a corporation's working capital remains frozen within illiquid physical stock before being successfully cleared through a final sale. It mathematically gauges the efficiency of the supply chain and demand forecasting algorithms, representing the holding period risk associated with storing, depreciating, and financing raw materials, work-in-progress, and finished goods.",
    "relevance": "A deteriorating (rising) Inventory Days profile often precedes catastrophic margin contraction and severe structural distress. It implies that consumer demand has sharply decelerated, leaving the enterprise holding obsolete or depreciating assets that necessitate massive, margin-destroying clearance discounts to liquidate. Conversely, an aggressively optimized, low DSI demonstrates fierce supply chain supremacy and robust product demand, maximizing inventory turnover velocity and drastically minimizing the capital intensity required to scale operations."
  },
  "Days Payable": {
    "meaning": "Days Payable Outstanding (DPO) is a core liquidity management metric indicating the average temporal duration a company takes to settle its trade credit obligations with its suppliers and vendors. It measures the extent to which a corporation utilizes its supply chain as an unsecuritized, zero-interest credit facility. Extending this duration allows the firm to retain internal cash reserves longer, effectively leveraging external supplier capital to fund immediate internal operational requirements or short-term yield-generating investments.",
    "relevance": "Sophisticated analysts view an expanded DPO as a hallmark of structural monopsony power and extreme market dominance. Mega-cap retailers and dominant manufacturers routinely dictate draconian payment terms (often 90 to 120 days) to weaker suppliers, generating an immense, structural negative working capital float. This structural float provides a massive competitive advantage by generating continuous, free operating leverage. However, sudden, involuntary spikes in DPO can conversely signal acute internal liquidity crises, wherein the firm is actively defaulting on supplier obligations to stave off imminent insolvency."
  },
  "Cash Cycle": {
    "meaning": "The Cash Conversion Cycle (CCC) is the ultimate holistic metric of working capital efficiency, representing the exact temporal duration, in days, that a firm's cash remains bound in the core operational loop. Calculated precisely as Inventory Days plus Debtor Days minus Days Payable, it measures the complete lifecycle from the initial deployment of cash for raw material procurement to the final collection of cash from the end consumer. It acts as the definitive timer on corporate liquidity velocity.",
    "relevance": "The CCC dictates a firm's fundamental capital intensity and organic scalability. A structurally protracted, positive CCC requires continuous, expensive external debt or equity financing to bridge the liquidity gap during growth phases, heavily dragging down return on invested capital. Conversely, elite enterprises often engineer a negative CCC—collecting cash from consumers immediately while delaying supplier payments for months. This creates a perpetual, self-funding capital engine where accelerating revenue growth mechanically floods the balance sheet with free, non-dilutive liquidity, an incredibly rare and valuable economic moat."
  },
  "Free Cash Flow (FCF) Generation": {
    "meaning": "Free Cash Flow (FCF) is the definitive, unadulterated metric of a corporation's true financial yield. It represents the residual, unencumbered liquidity generated by the core operational engine after rigorously stripping away all necessary capital expenditures (CapEx) required to maintain and expand the physical asset base. Unlike Net Income, which is heavily distorted by non-cash amortization, depreciation schedules, and accrual accounting conventions, FCF is the mathematically objective reality of the cash entering the corporate treasury.",
    "relevance": "Institutional analysts and sovereign wealth funds consider FCF the absolute nucleus of corporate valuation and capital allocation. Only genuine FCF can be legally and structurally utilized to fund non-dilutive dividend distributions, execute aggressive share repurchase programs, deleverage the balance sheet, or fund inorganic acquisitions. A firm reporting massive accounting profitability but chronically negative FCF is fundamentally a capital incinerator, relying entirely on the continuous goodwill of external debt and equity markets to stave off bankruptcy."
  },
  "Working Capital & Efficiency Days": {
    "meaning": "Working Capital Efficiency encompasses the rigorous management of the firm's short-term liquidity buffers, specifically optimizing the dynamic interplay between current assets (receivables, inventory) and current liabilities (payables). This cluster of metrics tracks the precise operational friction within the business model, monitoring the velocity at which the enterprise can transform raw inputs and credit sales back into unencumbered fiat currency without disrupting the supply chain or alienating the customer base.",
    "relevance": "Efficiency metrics are the ultimate leading indicators of impending financial distress or operational supremacy. Analysts dissect working capital cycles to detect accounting manipulation, channel stuffing, or severe demand destruction long before they manifest in top-line revenue declines. An expanding working capital requirement acts as a massive anchor on valuation multiples, whereas structural improvements in efficiency immediately unlock trapped liquidity, triggering upward revisions in discounted cash flow models and expanding the firm's theoretical intrinsic value."
  },
  "Capital Structure & Borrowings": {
    "meaning": "Capital Structure dictates the permanent financial architecture of the enterprise, delineating the exact proportionate weighting between permanent equity capital provided by shareholders and rigid, interest-bearing debt provided by institutional creditors. It outlines the firm's strategic risk tolerance, mapping the contractual, non-negotiable cash outflows required to service debt against the highly variable, discretionary cash flows generated by the underlying operations.",
    "relevance": "Evaluating Capital Structure is paramount for quantifying absolute insolvency risk and cost of capital optimization. While judicious leverage mechanically amplifies Return on Equity by utilizing cheap, tax-deductible debt to fund high-yielding assets, it concurrently introduces severe structural fragility. In macroeconomic environments characterized by rapidly tightening monetary policy or cyclical revenue contraction, highly levered structures face catastrophic refinancing risk, triggering immediate covenant breaches, credit rating downgrades, and the potential total obliteration of the equity tranche."
  },
  "Return Metrics (ROCE vs ROE)": {
    "meaning": "The comparative analysis of Return on Capital Employed (ROCE) versus Return on Equity (ROE) provides a surgical deconstruction of management's financial engineering versus their actual operational brilliance. ROCE evaluates the raw, unlevered return generated by the entire asset base, while ROE evaluates the levered return specifically isolated to the equity holders. The delta between these two metrics mathematically exposes the precise extent to which debt is being utilized to artificially inflate shareholder returns.",
    "relevance": "Institutional investors mandate a rigorous analysis of this spread to avoid value traps. If ROE is exceptionally high but ROCE is structurally mediocre, it indicates the firm is dangerously reliant on massive, unhedged debt layers to generate yield, masking a fundamentally flawed and commoditized business model. The most coveted enterprises exhibit incredibly high, organic ROCE figures that naturally cascade into high ROE without requiring any structural leverage, signifying a pristine balance sheet fortified by a monopolistic economic moat."
  },
  "Quarterly Profitability Momentum": {
    "meaning": "Quarterly Profitability Momentum analyzes the sequential (QoQ) and inter-year (YoY) velocity of core earnings, operating margins, and top-line revenue expansion on a high-frequency basis. It isolates the immediate operational trajectory of the firm, stripping away long-term historical smoothing to identify real-time inflection points, cyclical troughs, and the immediate materialization of macroeconomic headwinds or sudden supply chain efficiencies.",
    "relevance": "In highly sophisticated, algorithmic market environments, trailing annual data is entirely obsolete. Institutional capital aggressively prices equities based on the second derivative of growth—whether the rate of revenue and margin expansion is actively accelerating or decelerating in real-time. Monitoring quarterly momentum is critical for identifying structural turnaround narratives early, modeling imminent earnings surprises, and avoiding cyclical peaks where maximum historical earnings are masking a severely decaying forward fundamental outlook."
  },
  "Shareholding Pattern Distribution": {
    "meaning": "Shareholding Pattern Distribution provides a forensic mapping of the corporate equity capitalization table, segmenting ownership into strict institutional, insider, and retail tranches. It meticulously tracks the evolving capital commitments of corporate founders (Promoters), sophisticated global asset managers (FIIs), domestic mutual funds (DIIs), and the general retail public, illuminating the shifting conviction levels of the market's most informed and capitalized participants.",
    "relevance": "Analyzing capital flows within the shareholding structure is a critical component of institutional risk management. Sustained, aggressive accumulation by Promoters and institutional heavyweights (FIIs/DIIs) signals profound asymmetric conviction in forward earning potential and deep alignment of management interests. Conversely, sustained distribution by insiders or sophisticated funds into the hands of the retail public is universally recognized as a dire structural warning, heavily telegraphing impending operational distress, catastrophic earnings revisions, or severe corporate governance failures."
  },
  "DCF Intrinsic Value": {
    "meaning": "The Discounted Cash Flow (DCF) model is the definitive, mathematically rigorous framework for absolute asset valuation. It systematically projects the enterprise's entire stream of future unencumbered Free Cash Flows into perpetuity, and subsequently discounts them back to Present Value (PV) utilizing a meticulously calibrated Weighted Average Cost of Capital (WACC). This terminal valuation explicitly integrates the firm's systemic risk (Beta), the prevailing risk-free rate, and the structural equity risk premium into a singular, unified mathematical anchor.",
    "relevance": "DCF analysis completely immunizes the analyst from the volatile, emotion-driven pricing mechanisms of secondary markets, providing a cold, objective assessment of intrinsic economic worth. It forces analysts to rigorously underwrite long-term growth terminal rates, capital intensity, and structural margin decay, rather than relying on lazy, superficial multiple-expansion theories. If the quoted market capitalization trades at a steep mathematical discount to the meticulously modeled DCF output, it establishes the foundation for deep-value, alpha-generating capital deployment."
  },
  "Graham Number": {
    "meaning": "The Graham Number is a highly conservative, defensive valuation heuristic formulated by Benjamin Graham, heavily optimizing for absolute tangible asset protection and historical earnings stability. Calculated as the square root of 22.5 multiplied by the trailing Earnings Per Share (EPS) and the tangible Book Value Per Share (BVPS), it establishes a rigid, pessimistic ceiling on intrinsic value, mathematically barring the analyst from paying excessive premiums for highly speculative, unproven future growth trajectories.",
    "relevance": "In deep-value investment mandates, the Graham Number serves as a draconian filter for identifying severely dislocated, mathematically cheap assets. By anchoring valuation exclusively to hard, trailing fundamentals—demanding a P/E multiple no higher than 15x and a P/B multiple no higher than 1.5x—it completely insulates the portfolio from multiple-compression risk and growth-stock bubbles. While heavily criticized for its inability to accurately value modern, asset-light technology monopolies, it remains an indispensable, time-tested tool for navigating severe macroeconomic depressions and catastrophic market capitulations."
  },
  "Margin of Safety": {
    "meaning": "The Margin of Safety is the foundational epistemological principle of rigorous value investing. It is the explicit, mathematically enforced percentage differential between the asset's calculated underlying intrinsic value and its prevailing secondary market clearing price. It operates on the absolute assumption that all financial modeling, cash flow forecasting, and macro-economic predictions are inherently flawed, necessitating a massive structural buffer to absorb execution failure, statistical variance, and black-swan tail risks.",
    "relevance": "Institutional value managers strictly mandate a massive Margin of Safety (typically 20% to 40%) before authorizing capital deployment. This structural discount ensures that even if the enterprise severely underperforms management guidance, experiences unexpected margin compression, or faces a brutal macro-economic contraction, the absolute capital principal remains heavily protected from permanent impairment. It transitions investing from a high-risk probabilistic gamble into a highly fortified, mathematically asymmetrical operation focused entirely on capital preservation and downside mitigation."
  },
  "Piotroski F-Score": {
    "meaning": "The Piotroski F-Score is a rigorous, nine-point algorithmic framework designed to systematically quantify the fundamental, underlying health trajectory of an enterprise. By deeply interrogating the balance sheet and cash flow statements, it awards discrete binary points across three critical domains: structural profitability, leverage and liquidity stabilization, and operating efficiency. It is entirely devoid of market sentiment, focusing exclusively on the raw mathematical velocity of the firm's fundamental accounting metrics over a trailing period.",
    "relevance": "Quantitative funds and deep-value analysts deploy the F-Score as an automated, high-fidelity screener to ruthlessly separate genuine turnaround opportunities from terminal 'value traps'. A pristine score (8-9) mathematically confirms that the firm is actively deleveraging, expanding structural margins, and aggressively improving asset turnover. Conversely, a distressed score (0-3) acts as an incontrovertible alarm that the firm is hemorrhaging cash, aggressively accumulating toxic debt, and facing an exponentially accelerating trajectory toward absolute structural insolvency."
  },
  "Altman Z-Score": {
    "meaning": "The Altman Z-Score is an advanced multivariate statistical model explicitly engineered to predict the probability of corporate bankruptcy and structural insolvency within a strict 24-month horizon. It mathematically synthesizes five distinct, heavily weighted financial ratios—encompassing working capital liquidity, cumulative retained earnings, operational profitability, market leverage, and capital efficiency—into a singular, highly predictive credit-risk scalar.",
    "relevance": "In distressed debt, high-yield fixed income, and deep-value equity markets, the Z-Score is an indispensable tool for quantifying extreme tail risk. A score languishing below 1.8 unequivocally categorizes the enterprise within the 'Distress Zone,' signaling an acute, highly elevated probability of imminent default and the complete obliteration of the equity tranche. Conversely, a resilient score exceeding 3.0 provides robust mathematical confirmation of a fortified, unshakeable balance sheet capable of effortlessly absorbing severe, protracted macro-economic shocks without necessitating dilutive external financing."
  },
  "DuPont ROE Decomposition": {
    "meaning": "The DuPont Analysis is a surgical, forensic deconstruction of the Return on Equity (ROE) metric. Rather than accepting a monolithic ROE figure at face value, this analytical framework fractures the return into three distinct operational vectors: Net Profit Margin (operating efficiency), Asset Turnover (capital velocity), and the Equity Multiplier (financial leverage). This mathematical autopsy reveals the exact mechanical drivers responsible for the firm's compounding velocity, exposing whether the returns are organically driven by elite business execution or artificially manufactured via massive balance sheet engineering.",
    "relevance": "Sophisticated institutional analysts mandate DuPont decomposition to rigorously validate the quality, sustainability, and risk profile of a firm's equity returns. A rising ROE driven purely by expanding net margins and accelerating asset turnover indicates a dominant, highly scalable franchise expanding its economic moat. However, if the entire ROE expansion is mathematically traced back to a surging Equity Multiplier, it serves as a massive red flag—the management team is actively masking operational decay by recklessly loading the balance sheet with toxic debt, severely escalating the enterprise's systemic vulnerability to interest rate shocks."
  },
  "Debt Coverage & Efficiency": {
    "meaning": "Debt Coverage metrics, anchored primarily by the Interest Coverage Ratio (EBIT divided by Interest Expense) and the Debt-to-EBITDA multiple, provide a rigorous stress-test of the firm's ability to service its permanent capital obligations. These metrics quantify the absolute mathematical buffer between the firm's core operational cash generation and the rigid, non-negotiable cash outflows demanded by institutional creditors. It effectively maps the firm's margin for error before triggering a catastrophic technical default.",
    "relevance": "In credit analysis and corporate restructuring, these metrics are paramount. An Interest Coverage Ratio structurally plunging below 2.0x signals extreme financial fragility, implying that minor demand destruction or slight margin compression will immediately plunge the firm into insolvency. Highly efficient, elite enterprises typically maintain coverage ratios well in excess of 10.0x, ensuring that even during brutal macro-economic recessions, the balance sheet remains heavily fortified, completely insulating the common equity holders from the threat of restructuring or chapter 11 reorganization."
  },
  "Consolidated / Standalone": {
    "meaning": "The bifurcation between Consolidated and Standalone financial reporting is a critical accounting distinction for multi-tiered corporate structures, holding companies, and global conglomerates. Standalone statements surgically isolate the financial operations, debt load, and revenue generation strictly native to the parent entity itself, entirely ignoring its web of subsidiaries. Consolidated statements mathematically aggregate and synthesize the total assets, liabilities, and cash flows of the parent company alongside every single controlled subsidiary, joint venture, and special purpose vehicle, providing a unified, holistic ledger of the entire corporate empire.",
    "relevance": "Analyzing standalone figures for vast conglomerates is exceptionally dangerous and frequently misleading, as management can aggressively shift toxic debt into opaque subsidiaries while funneling pristine dividend streams back to the parent entity. Institutional analysts strictly mandate the analysis of Consolidated financial statements to calculate the true, aggregate systemic leverage, total enterprise value, and holistic operational cash flow of the organization, entirely neutralizing any accounting arbitrage or structural obfuscation attempted via complex subsidiary networks."
  }
};

const output = `const deepTooltips = ${JSON.stringify(deepTooltips, null, 2)};`;
fs.writeFileSync('app/static/deep_tooltips.js', output);
